{% set name = "cvxpy" %}
{% set version = "1.0.31" %}
{% set sha256 = "b398754f9e9ceaa46b07806b5ae85f90fd8de748475db22a6b99c5943cebe69d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cvxpy = cvxpy:main
    #
    # Would create an entry point called cvxpy that calls cvxpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

outputs:
  - name: cvxpy
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('cvxpy-base', exact=True) }}
    test:
      imports:
        - cvxpy
        - cvxpy.cvxcore
        - cvxpy.cvxcore.python
      requires:
        - nose
      commands:
        - nosetests cvxpy
  - name: cvxpy-base
    build:
      script: python -m pip install . --no-deps --ignore-installed --no-use-pep517 -vvv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
        - numpy
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - osqp >=0.4.1
        - ecos >=2
        - scs >=1.1.3
        - scipy >=1.1.0
        - multiprocess
        - fastcache
        - six

about:
  home: https://www.cvxpy.org/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
  doc_url: https://www.cvxpy.org/
  dev_url: http://github.com/cvxgrp/cvxpy/

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
